version: "3"

services:
  app:
    container_name: "flask_app"
    restart: always
    build: .
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi:app
      - FLASK_DEBUG=1
      - FLASK_PORT=${FLASK_PORT}
    ports:
      - 127.0.0.1:9191:${FLASK_PORT}
    entrypoint: "bash entry-point.sh"

  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: react_app
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:80
